INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);
INSERT INTO users (name, age) VALUES ("name", 1);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 10, "start date", "end date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 10, "start date", "end date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 10, "start date", "end date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 10, "start date", "end date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 10, "start date", "end date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 10, "start date", "end date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 10, "start date", "end date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 10, "start date", "end date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 10, "start date", "end date");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 10, "start date", "end date");

INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);